SanThuongMaiG15/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using SanThuongMaiG15.Models;

namespace SanThuongMaiG15.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly EcC2C_2Context _context;

        public AdminProductsController(EcC2C_2Context context)
        {
            _context = context;
        }

        // GET: Admin/AdminProducts
        public async Task<IActionResult> Index(int page = 1, int CatID = 0)
        {
            var pageNumber = page;

            var pageSize = 20;

            List<Product> lsProducts = new List<Product>();
            if (CatID != 0)
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Where(x => x.CatId == CatID )
                .Include(x => x.Cat)
                .OrderByDescending(x => x.ProductId).ToList();
            }
            else
            {
                lsProducts = _context.Products
                .AsNoTracking()
                .Include(x => x.Cat)
                .OrderByDescending(x => x.ProductId).ToList();
            }

            PagedList<Product> models = new PagedList<Product>(lsProducts.AsQueryable(), pageNumber, pageSize);
            ViewBag.CurrentCateID = CatID;
            ViewBag.currentPage = pageNumber;


            ViewData["DanhMuc"] = new SelectList(_context.Categories, "CatId", "CatName", CatID);

            return View(models);
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .Include(p => p.Seller)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName");
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "Email");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,Description,CatId,Price,Quantity,SellerId,DatePosted,ImageUrl,ProductStatus,Thumb")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "Email", product.SellerId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "Email", product.SellerId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,Description,CatId,Price,Quantity,SellerId,DatePosted,ImageUrl,ProductStatus,Thumb")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CatId"] = new SelectList(_context.Categories, "CatId", "CatName", product.CatId);
            ViewData["SellerId"] = new SelectList(_context.Users, "UserId", "Email", product.SellerId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Cat)
                .Include(p => p.Seller)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Admin/AdminProducts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

SanThuongMaiG15/Areas/Admin/Views/AdminProducts/Create.cshtml
@model SanThuongMaiG15.Models.Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class ="form-control" asp-items="ViewBag.CatId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SellerId" class="control-label"></label>
                <select asp-for="SellerId" class ="form-control" asp-items="ViewBag.SellerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="DatePosted" class="control-label"></label>
                <input asp-for="DatePosted" class="form-control" />
                <span asp-validation-for="DatePosted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductStatus" class="control-label"></label>
                <input asp-for="ProductStatus" class="form-control" />
                <span asp-validation-for="ProductStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SanThuongMaiG15/Areas/Admin/Views/AdminProducts/Delete.cshtml
@model SanThuongMaiG15.Models.Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Xác nhận xóa sản phẩm</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin quyền sản phẩm</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>@Model.ProductName</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                    <tr>
                        <td>Đơn giá:</td>
                        <td>@Model.Price</td>
                    </tr>
                    <tr>
                        <td>Số lượng:</td>
                        <td>@Model.Quantity</td>
                    </tr>
                    <tr>
                        <td>Ngày đăng:</td>
                        <td>@Model.DatePosted</td>
                    </tr>
                    <tr>
                        <td>Đường dẫn ảnh:</td>
                        <td>@Model.ImageUrl</td>
                    </tr>
                    <tr>
                        <td>Trạng thái:</td>
                        <td>@Model.ProductStatus</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                    <tr>
                        <td>Danh mục:</td>
                        <td>@Model.Cat.CatName</td>
                    </tr>
                    <tr>
                        <td>Email người bán:</td>
                        <td>@Model.Seller.Email</td>
                    </tr>
                    <tr>
                        <td>Delete</td>
                        <td>
                            <form asp-action="Delete" asp-route-id="@Model.ProductId">
                                <input type="hidden" asp-for="ProductId" />
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

SanThuongMaiG15/Areas/Admin/Views/AdminProducts/Details.cshtml
@model SanThuongMaiG15.Models.Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a class="breadcrumb-item" asp-area="Admin" asp-controller="AdminProducts" asp-action="Index">Danh sách sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin sản phẩm</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin quyền sản phẩm</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.ProductId</td>
                    </tr>
                    <tr>
                        <td>Tên sản phẩm:</td>
                        <td>@Model.ProductName</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                    <tr>
                        <td>Đơn giá:</td>
                        <td>@Model.Price</td>
                    </tr>
                    <tr>
                        <td>Số lượng:</td>
                        <td>@Model.Quantity</td>
                    </tr>
                    <tr>
                        <td>Ngày đăng:</td>
                        <td>@Model.DatePosted</td>
                    </tr>
                    <tr>
                        <td>Đường dẫn ảnh:</td>
                        <td>@Model.ImageUrl</td>
                    </tr>
                    <tr>
                        <td>Trạng thái:</td>
                        <td>@Model.ProductStatus</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.Description</td>
                    </tr>
                    <tr>
                        <td>Danh mục:</td>
                        <td>@Model.Cat.CatName</td>
                    </tr>
                    <tr>
                        <td>Email người bán:</td>
                        <td>@Model.Seller.Email</td>
                    </tr>
                    
                </tbody>
            </table>
        </div>
    </div>
</div>

SanThuongMaiG15/Areas/Admin/Views/AdminProducts/Edit.cshtml
@model SanThuongMaiG15.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatId" class="control-label"></label>
                <select asp-for="CatId" class="form-control" asp-items="ViewBag.CatId"></select>
                <span asp-validation-for="CatId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SellerId" class="control-label"></label>
                <select asp-for="SellerId" class="form-control" asp-items="ViewBag.SellerId"></select>
                <span asp-validation-for="SellerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DatePosted" class="control-label"></label>
                <input asp-for="DatePosted" class="form-control" />
                <span asp-validation-for="DatePosted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductStatus" class="control-label"></label>
                <input asp-for="ProductStatus" class="form-control" />
                <span asp-validation-for="ProductStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Thumb" class="control-label"></label>
                <input asp-for="Thumb" class="form-control" />
                <span asp-validation-for="Thumb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SanThuongMaiG15/Areas/Admin/Views/AdminProducts/Index.cshtml
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<SanThuongMaiG15.Models.Product>

@{
    ViewData["Title"] = "Quản lý sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
<div class="header-sub-title">
    <nav class="breadcrumb breadcrumb-dash">
        <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
        <span class="breadcrumb-item active">Danh sách sản phẩm</span>
    </nav>
</div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class="d-md-flex">
                    <div class="m-b-10 m-r-15">
                        <select class="custom-select" id="txtCatID" name="txtCatID" style="min-width: 200px;" asp-items="ViewBag.DanhMuc">
                            <option disabled selected>Chọn Danh Mục</option>
                            <option value="0">All</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Tên sản phẩm</th>
                        <th>Danh mục</th>
                        <th>Giá</th>
                        <th>Tồn kho</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (@Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.ProductId
                                </td>
                                <td>
                                    @item.ProductName
                                </td>
                                <td>@item.Cat.CatName</td>
                                <td>@item.Price $</td>

                                <td>@item.Quantity</td>
                                <td>
                                    @if (item.Quantity > 0)
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Còn hàng</div>
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="d-flex align-items-center">
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <div>Hết hàng</div>
                                        </div>
                                    }

                                </td>
                                <td>
                                    <a class="btn btn-primary m-r-5" asp-area="Admin" asp-controller="AdminProducts" asp-action="Details" asp-route-id="@item.ProductId">View</a>
                                    @* <a class="btn btn-secondary m-r-5 " asp-area="Admin" asp-controller="AdminProducts" asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> *@
                                    <a class="btn btn-success m-r-5" asp-area="Admin" asp-controller="AdminProducts" asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>

                                </td>
                            </tr>

                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Admin" asp-controller="AdminProducts" asp-route-CatID="ViewBag.CurrentCateID" asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>