SanThuongMaiG15/Areas/Seller/Controllers/SellerOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using SanThuongMaiG15.Models;

namespace SanThuongMaiG15.Areas.Seller.Controllers
{
    [Area("Seller")]
    public class SellerOrdersController : Controller
    {
        private readonly EcC2C_2Context _context;

        public SellerOrdersController(EcC2C_2Context context)
        {
            _context = context;
        }

        // GET: Seller/SellerOrders
        public IActionResult Index(int? page )
        {
            var pageNumber = page == null || page <= 0 ? 1 : page.Value;

            var pageSize = 20;

          
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            else
            {
                Console.WriteLine($"Authenticated User: {User.Identity.Name}");
            }

            
            var email = User.Identity.Name;

            var seller = _context.Users.FirstOrDefault(u => u.Email == email);

            

       

            var Orders = _context.Orders
                .Include(o => o.Buyer)
                .Include(o => o.TransactStatus)
                .Include(o => o.OrderDetails) // Bao gồm chi tiết đơn hàng
                .ThenInclude(od => od.Product) // Bao gồm sản phẩm
                .AsNoTracking()
                .Where(o => o.OrderDetails.Any(od => od.Product.SellerId == seller.UserId)) // Điều kiện lọc
                .OrderByDescending(o => o.OrderDate);

            PagedList<Order> models = new PagedList<Order>(Orders, pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;

            return View(models);

        }

        // GET: Seller/SellerOrders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Buyer)
                .Include(o => o.TransactStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }
            var Chitietdonhang = _context.OrderDetails
                .Include(o => o.Product)
                .AsNoTracking()
                .Where(x => x.OrderId == order.OrderId)
                .OrderBy(x=>x.OrderDetailId).ToList();
            ViewBag.ChiTiet = Chitietdonhang;
            return View(order);
        }

        // GET: Seller/SellerOrders/Create
        public IActionResult Create()
        {
            ViewData["BuyerId"] = new SelectList(_context.Users, "UserId", "Email");
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status");
            return View();
        }

        // POST: Seller/SellerOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,BuyerId,OrderDate,TransactStatusId,TotalMoney,Note,Address,PaymentId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuyerId"] = new SelectList(_context.Users, "UserId", "Email", order.BuyerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return View(order);
        }


        // GET: Seller/SellerOrders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["BuyerId"] = new SelectList(_context.Users, "UserId", "Email", order.BuyerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return View(order);
        }


        // POST: Seller/SellerOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,BuyerId,OrderDate,TransactStatusId,TotalMoney,Note,Address,PaymentId")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BuyerId"] = new SelectList(_context.Users, "UserId", "Email", order.BuyerId);
            ViewData["TransactStatusId"] = new SelectList(_context.TransactStatuses, "TransactStatusId", "Status", order.TransactStatusId);
            return View(order);
        }

        // GET: Seller/SellerOrders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Buyer)
                .Include(o => o.TransactStatus)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Seller/SellerOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.Orders.FindAsync(id);
            _context.Orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.Orders.Any(e => e.OrderId == id);
        }
    }
}

SanThuongMaiG15/Areas/Seller/Views/SellerOrders/Create.cshtml
@model SanThuongMaiG15.Models.Order

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Seller/Views/Shared/_SellerLayout.cshtml";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BuyerId" class="control-label"></label>
                <select asp-for="BuyerId" class ="form-control" asp-items="ViewBag.BuyerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class ="form-control" asp-items="ViewBag.TransactStatusId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TotalMoney" class="control-label"></label>
                <input asp-for="TotalMoney" class="form-control" />
                <span asp-validation-for="TotalMoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label"></label>
                <input asp-for="PaymentId" class="form-control" />
                <span asp-validation-for="PaymentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SanThuongMaiG15/Areas/Seller/Views/SellerOrders/Delete.cshtml
@model SanThuongMaiG15.Models.Order

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Seller/Views/Shared/_SellerLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Order</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalMoney)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalMoney)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Buyer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Buyer.Email)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactStatus.Status)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SanThuongMaiG15/Areas/Seller/Views/SellerOrders/Details.cshtml
@model SanThuongMaiG15.Models.Order

@{
    ViewData["Title"] = "Thông tin đơn hàng #" + Model.OrderId;
    Layout = "~/Areas/Seller/Views/Shared/_SellerLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}
    <div class="main-content">
        <div class="page-header">
            <div class="header-sub-title">
                <nav class="breadcrumb breadcrumb-dash">
                    <a asp-area="Seller" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                    <a class="breadcrumb-item" asp-area="Seller" asp-controller="SellerOrders" asp-action="Index">Thông tin đơn hàng</a>
                    <span class="breadcrumb-item active">Chi tiết đơn hàng</span>
                </nav>
            </div>
        </div>
        <div class="container">
            <div class="card">
                <div class="card-body">
                    <div id="invoice" class="p-h-30">
                        <div class="row m-t-20 lh-2">
                            <div class="col-sm-6">
                            <h3 class="p-l-10 m-t-10">Chi tiết đơn hàng:</h3>
                                <address class="p-l-10 m-t-10">
                                    <span class="font-weight-semibold text-dark">@Model.Buyer.Username</span><br>
                                    <span>@Model.Address </span><br>
                                    <span>@Model.Buyer.PhoneNumber</span>
                                </address>
                            </div>
                            <div class="col-sm-6">
                                <div class="m-t-80">
                                    <div class="text-dark text-uppercase d-inline-block">
                                        <span class="font-weight-semibold text-dark">Mã đơn hàng :</span>
                                    </div>
                                    <div class="float-right">@Model.BuyerId</div>
                                </div>
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Ngày mua :</span>
                                </div>
                                <div class="float-right">@Model.OrderDate</div>
                                <br />
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Trạng thái đơn hàng :</span>
                            </div>
                            <div class="float-right">@Model.TransactStatus.Status</div>
                            </div>
                        </div>
                        <div class="m-t-20">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                       <tr>
                                            <th>No.</th>
                                            <th>Tên sản phẩm</th>
                                            <th>Số lượng</th>
                                            <th>Đơn giá</th>
                                            <th>Tổng tiền</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if(orderDetails!=null && orderDetails.Count() > 0)
                                        {
                                            int i = 1;
                                            foreach (var item in orderDetails)
                                            {
                                                <tr>
                                                    <th>@i</th>
                                                    <td>@item.Product.ProductName</td>
                                                    <td>@item.Quantity</td>
                                                    <td>@item.Price $</td>
                                                    <td>@item.TotalMoney $</td>
                                                </tr>
                                                i++;

                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <div class="row m-t-30 lh-1-8">
                                <div class="col-sm-12">
                                    <div class="float-right text-right">
                                        <h3><span class="font-weight-semibold text-dark">Tổng tiền :</span> @Model.TotalMoney $</h3>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

SanThuongMaiG15/Areas/Seller/Views/SellerOrders/Edit.cshtml
@model SanThuongMaiG15.Models.Order

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Seller/Views/Shared/_SellerLayout.cshtml";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <div class="form-group">
                <label asp-for="BuyerId" class="control-label"></label>
                <select asp-for="BuyerId" class="form-control" asp-items="ViewBag.BuyerId"></select>
                <span asp-validation-for="BuyerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactStatusId" class="control-label"></label>
                <select asp-for="TransactStatusId" class="form-control" asp-items="ViewBag.TransactStatusId"></select>
                <span asp-validation-for="TransactStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalMoney" class="control-label"></label>
                <input asp-for="TotalMoney" class="form-control" />
                <span asp-validation-for="TotalMoney" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PaymentId" class="control-label"></label>
                <input asp-for="PaymentId" class="form-control" />
                <span asp-validation-for="PaymentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SanThuongMaiG15/Areas/Seller/Views/SellerOrders/Index.cshtml
@using PagedList.Core.Mvc;
@model PagedList.Core.IPagedList<SanThuongMaiG15.Models.Order>

@{
    ViewData["Title"] = "Quản lý đơn hàng";
    Layout = "~/Areas/Seller/Views/Shared/_SellerLayout.cshtml";
}

<div class="page-header">
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Seller" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Danh sách đơn hàng</span>
        </nav>
    </div>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
            </div>    
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Người mua</th>
                        <th>Ngày mua</th>
                        <th>Tổng tiền</th>
                        <th>Trạng thái</th>
                        <th>#</th>
                    </tr>
                </thead>
                <tbody>
                    @if (@Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.OrderId
                                </td>
                                <td>
                                    @item.Buyer.Email
                                </td>
         
                                <td>@item.OrderDate</td>
                                <td>@item.TotalMoney $</td>

                                <td>@item.TransactStatus.Status</td>
                                
                                <td>
                                    <a class="btn btn-primary m-r-5" asp-area="Seller" asp-controller="SellerOrders" asp-action="Details" asp-route-id="@item.OrderId">Xem đơn hàng</a>
                                    <a class="btn btn-secondary m-r-5 " asp-area="Seller" asp-controller="SellerOrders" asp-action="Edit" asp-route-id="@item.OrderId">Chỉnh sửa</a>
                                    <a class="btn btn-success m-r-5" asp-area="Seller" asp-controller="SellerOrders" asp-action="Delete" asp-route-id="@item.OrderId">Xóa</a>

                                </td>
                            </tr>

                        }
                    }


                </tbody>
            </table>
            <div aria-label="Page navigation example">
                <ul class="pagination">
                    <pager class="pager-container" list="@Model" asp-area="Seller" asp-controller="SellerOrders"  asp-action="Index" />
                </ul>
            </div>
        </div>
    </div>
</div>